version: '3.1'

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    build:
      context: ./Docker
      dockerfile: db.Dockerfile
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: myUser
      POSTGRES_DB: myappdb
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8083:80