version: '3.1'

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: <example>
      POSTGRES_USER: <example>
      POSTGRES_DB: <myapp>
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8083:80
